### ISSUE TITLE
NPE in BleManagerGattCallback.onDeviceReady (BleManager.java:2215)

### ISSUE THREAD

**Issue by Maragues** [NordicSemiconductor/Android-BLE-Library#156] opened 2020-02-04 14:21 UTC
version: 2.1.1

```
Caused by java.lang.NullPointerException
Attempt to invoke virtual method 'android.bluetooth.BluetoothDevice android.bluetooth.BluetoothGatt.getDevice()' on a null object reference
no.nordicsemi.android.ble.BleManager$BleManagerGattCallback.onDeviceReady (BleManager.java:2215)
no.nordicsemi.android.ble.BleManager$BleManagerGattCallback.nextRequest (BleManager.java:3158)
no.nordicsemi.android.ble.BleManager$BleManagerGattCallback.nextRequest (BleManager.java:3222)
no.nordicsemi.android.ble.BleManager$BleManagerGattCallback.nextRequest (BleManager.java:3222)
no.nordicsemi.android.ble.BleManager$BleManagerGattCallback.nextRequest (BleManager.java:3222)
no.nordicsemi.android.ble.BleManager$BleManagerGattCallback.onServicesDiscoveredSafe (BleManager.java:2613)
no.nordicsemi.android.ble.MainThreadBluetoothGattCallback.lambda$onServicesDiscovered$1 (MainThreadBluetoothGattCallback.java:112)
```

Reported by Firebase on a Xiaomi Redmi Note 5 Pro on Android 9

**Comment by philips77** [comment] 2020-02-05 08:54
Possible duplicate of #7 and for sure duplicate of #88. This issue will be fixed in 2.2.0 version. Thank you for creating the issue.

**Closed by philips77** 2020-02-05 08:54 UTC
