### ISSUE TITLE
Bytes lost when receiving notifications

### ISSUE THREAD

**Issue by WuLFGit** [NordicSemiconductor/Android-BLE-Library#129] opened 2019-09-24 15:34 UTC
---

I tried to provision a device multiple times failing using no.nordicsemi.android:ble:2.1.1 version. Switching back to no.nordicsemi.android:ble:1.2.0 makes provisioning work back again. What i noticed is a difference between response byte array i receive when sending public key to my device. 

May i ask you why this behaviour happens? It sounds weird to me that switching ble library version result in different byte array response received from the device.

**Logs / Screenshots**
Here some screenshot about responses i receive when public key is sent:

Public key sent response on no.nordicsemi.android:ble:2.1.1. As you can notice, on position 1 i expect value 3 but i receive -99:
![image](https://user-images.githubusercontent.com/16474620/65496005-f4442980-deb7-11e9-83cb-70563f1d0df6.png)

Public key sent response on no.nordicsemi.android:ble:1.2.0. As you can notice, on position 1 there is the expected value 3:
![image](https://user-images.githubusercontent.com/16474620/65496102-2a81a900-deb8-11e9-9eba-e4574178cf5b.png)

Responses length is different also.

Thank you in advance for you support.

**Comment by roshanrajaratnam** [comment] 2019-09-25 06:37
Duplicate of https://github.com/NordicSemiconductor/Android-nRF-Mesh-Library/issues/250

**Comment by philips77** [comment] 2019-10-30 10:31
I will take the issue in this project.

**Comment by philips77** [comment] 2019-10-30 10:38
Could you post the logs from your app (that's using BLE library version 2.x) and some code snippets how do you request and set the callbacks? Do you set MTU to 250+? Are you sure the response you get using version 2 isn't a correct response, but the request is invalid, so the device sends an error message instead of Composition Data Status?

**Comment by philips77** [comment] 2019-10-30 21:25
I hoped that you have this integration with BLE library 2.x somewhere on another branch. As I said, to help you I need the logs and snippet of your code to check if your implemention is correct.
As I understand, the issue is that the old version of the library returns correct value of the received notification (66 bytes, not 20, as would be received issuing mtu=23), but the new version returns only 28 bytes. Isn't that right? The values are then combined from multiple notifications using the mesh proxy protocol, but as you're reporting this issue for the BLE library, I understand that the very low layer has an issue, not the concatenation. But now, when you're saying that the mtu is set to 23, that would mean that the status displayed above are already combined from 2+ notifications. As you see, without the logs I can't really say much.

**Comment by philips77** [comment] 2019-11-08 12:00
I've migrated nRF Mesh for Android to use BLE Library 2.1.1 and could not replicate this issue.

**Comment by philips77** [comment] 2019-11-25 13:05
Issue fixed in nRF Mesh library. It was a MTU issue. The `mMtu` variable wasn't reset on disconnection, so next time the same manager was used for a different connection when the MTU was successfully set on the previous time, the MTU request was no longer performed.

**Comment by philips77** [comment] 2019-11-25 13:43
Fixed internally.

**Closed by philips77** 2019-11-25 13:43 UTC
Labels: duplicate
