### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean no.nordicsemi.android.ble.p.f()' on a null object reference

### ISSUE THREAD

**Issue by qq1012298028** [NordicSemiconductor/Android-BLE-Library#62] opened 2018-12-14 07:36 UTC
```
1 no.nordicsemi.android.ble.a.internalConnect(BleManager.java:791)
2 no.nordicsemi.android.ble.a.access$2100(BleManager.java:113)
3 no.nordicsemi.android.ble.a$a.lambda$onConnectionStateChangeSafe$1$BleManager$BleManagerGattCallback(BleManager.java:2442)
4 no.nordicsemi.android.ble.i.run(Unknown Source:4)
5 android.os.Handler.handleCallback(Handler.java:790)
6 android.os.Handler.dispatchMessage(Handler.java:99)
7 android.os.Looper.loop(Looper.java:164)
8 android.app.ActivityThread.main(ActivityThread.java:6753)
9 java.lang.reflect.Method.invoke(Native Method)
10 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:482)
11 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by philips77** [comment] 2018-12-14 09:30
Duplicate of #61

**Closed by philips77** 2018-12-14 09:30 UTC
