### ISSUE TITLE
NRF ToolBox UART De-Bugging

### ISSUE THREAD

**Issue by VinayTShetty** [NordicSemiconductor/Android-BLE-Library#147] opened 2020-01-06 11:28 UTC
Hi ,
frist of all thanks for providing the source for this application.[NRF Toolbox](https://github.com/NordicSemiconductor/Android-nRF-Toolbox).
Here i am De-Bugging the application for the UART in that i am seeing a Connection is done using
Google API.(Screen Shot i have attached).
![Capture](https://user-images.githubusercontent.com/33421892/71815464-907bf000-30a5-11ea-802a-a043d61c421b.PNG)
But the documentation says that UART is using below code to do the connection.[Link](https://github.com/NordicSemiconductor/Android-BLE-Library)
![Capture1](https://user-images.githubusercontent.com/33421892/71815499-abe6fb00-30a5-11ea-961a-33e13cd5a597.PNG)
which is the actually right...?

can you please provide the code where the BLE library is used...
so that it will be easy to De-Bug.

**Comment by philips77** [comment] 2020-01-06 12:47
Duplicate of #146

**Closed by philips77** 2020-01-06 12:47 UTC
