### ISSUE TITLE
Problems with writing Tests

### ISSUE THREAD

**Issue by ChiangChu** [NordicSemiconductor/Android-BLE-Library#205] opened 2020-06-22 08:05 UTC
Hello guys,

It seems like it is not possible to write tests with your library, 'cause it returns a BluetoothDevice which cant be mocked (At least so far I know).

Is there anyway to tell your library it should emulate a connected device so I can test my functionality which relies on a connected device?

**Comment by philips77** [comment] 2020-06-23 07:29
Yes, testing is still problematic. We have #45 open and I hope it will be fixed one day. Unfortunately I have no time to look into this now :(

**Comment by philips77** [comment] 2020-06-24 09:16
Duplicate of #45

**Closed by philips77** 2020-06-24 09:16 UTC
